version: '2'

services:
    db:
        image: mysql:latest
        volumes:
            - ${DATABASE_DATA_DIR}:/var/lib/mysql
#            - ${DATABASE_LOG_DIR}:/var
        ports:
            - "${DATABASE_PORT}:3306"
        environment:
            - MYSQL_ROOT_PASSWORD=${DATABASE_ROOT_PASSWORD}
            - MYSQL_DATABASE=${DATABASE_NAME}
            - MYSQL_USER=${DATABASE_USER}
            - MYSQL_PASSWORD=${DATABASE_PASSWORD}

    phpmyadmin:
        image: phpmyadmin/phpmyadmin:latest
        ports:
            - "${PHP_MY_ADMIN_PORT}:80"
        links:
          - db:mysql

    app-back:
        build:
            context: ${DOCKER_FILES_BACK_DIR}
        ports:
            - "${HOST_PORT}:80"
            - "9090:9090"
        environment:
            - DATABASE_HOST=${DATABASE_HOST}
            - DATABASE_PORT=${DATABASE_PORT}
            - DATABASE_NAME=${DATABASE_NAME}
            - DATABASE_USER=${DATABASE_USER}
            - DATABASE_PASSWORD=${DATABASE_PASSWORD}
        volumes:
            - ${APP_DIR}:/var/www/html
            - ${COMPOSER_DIR}:/root/.composer
            - ${BACK_APACHE_LOG_DIR}:/var/log/apache2
            - ${BACK_SYMFONY_LOG_DIR}:/var/www/html/var/logs
        links:
            - db
