version: '3'

services:
    db:
        image: mysql:latest
        volumes:
            - "./docker/db:/var/lib/mysql"
        ports:
            - "${DATABASE_PORT}:3306"
        environment:
            - MYSQL_ROOT_PASSWORD=${DATABASE_ROOT_PASSWORD}
            - MYSQL_DATABASE=${DATABASE_NAME}
            - MYSQL_USER=${DATABASE_USER}
            - MYSQL_PASSWORD=${DATABASE_PASSWORD}
        networks:
            - back

    phpmyadmin:
        image: phpmyadmin/phpmyadmin:latest
        ports:
            - "${PHP_MY_ADMIN_PORT}:80"
        links:
          - db:mysql
        networks:
            - back

    app-back:
        build:
            context: ./docker/back
            dockerfile: ./Dockerfile
        ports:
            - "${HOST_PORT}:80"
            - "9090:9090"
        environment:
            - SF_ENV=${SF_ENV}
            - DATABASE_HOST=${DATABASE_HOST}
            - DATABASE_PORT=${DATABASE_PORT}
            - DATABASE_NAME=${DATABASE_NAME}
            - DATABASE_USER=${DATABASE_USER}
            - DATABASE_PASSWORD=${DATABASE_PASSWORD}
        volumes:
            - "${APP_DIR}:/var/www/html"
            - "${COMPOSER_DIR}:/root/.composer"
            - "./docker/back/log:/var/log"
        links:
            - db
        networks:
            - back

networks:
    front:
    back:
